package com.kickstarter;

import com.kickstarter.libs.CurrentUser;
import com.kickstarter.libs.Koala;
import com.kickstarter.libs.KoalaTrackingClient;
import com.kickstarter.libs.Money;
import com.kickstarter.libs.utils.ApplicationLifecycleUtil;
import com.kickstarter.presenters.ActivityFeedPresenter;
import com.kickstarter.presenters.CommentFeedPresenter;
import com.kickstarter.presenters.DiscoveryFilterPresenter;
import com.kickstarter.presenters.DiscoveryPresenter;
import com.kickstarter.presenters.FacebookConfirmationPresenter;
import com.kickstarter.presenters.LoginPresenter;
import com.kickstarter.presenters.LoginToutPresenter;
import com.kickstarter.presenters.ProfilePresenter;
import com.kickstarter.presenters.ProjectPresenter;
import com.kickstarter.presenters.ResetPasswordPresenter;
import com.kickstarter.presenters.SearchPresenter;
import com.kickstarter.presenters.SignupPresenter;
import com.kickstarter.presenters.ThanksPresenter;
import com.kickstarter.presenters.TwoFactorPresenter;
import com.kickstarter.presenters.ViewPledgePresenter;
import com.kickstarter.services.gcm.MessageService;
import com.kickstarter.services.gcm.RegisterService;
import com.kickstarter.ui.activities.ActivityFeedActivity;
import com.kickstarter.ui.activities.CommentFeedActivity;
import com.kickstarter.ui.activities.DiscoveryActivity;
import com.kickstarter.ui.activities.HelpActivity;
import com.kickstarter.ui.activities.ProfileActivity;
import com.kickstarter.ui.activities.ProjectActivity;
import com.kickstarter.ui.activities.ViewPledgeActivity;
import com.kickstarter.ui.toolbars.DiscoveryToolbar;
import com.kickstarter.ui.viewholders.CommentViewHolder;
import com.kickstarter.ui.viewholders.DiscoveryFilterViewHolder;
import com.kickstarter.ui.viewholders.EmptyActivityFeedViewHolder;
import com.kickstarter.ui.viewholders.EmptyCommentFeedViewHolder;
import com.kickstarter.ui.viewholders.ProjectCardViewHolder;
import com.kickstarter.ui.viewholders.ProjectContextViewHolder;
import com.kickstarter.ui.viewholders.ProjectStateChangedPositiveViewHolder;
import com.kickstarter.ui.viewholders.ProjectViewHolder;
import com.kickstarter.ui.viewholders.RewardViewHolder;
import com.kickstarter.ui.views.IconTextView;
import com.kickstarter.ui.views.KSWebView;

public interface ApplicationGraph {
  void inject(ActivityFeedActivity __);
  void inject(ActivityFeedPresenter __);
  void inject(ApplicationLifecycleUtil __);
  void inject(CommentFeedActivity __);
  void inject(CommentFeedPresenter __);
  void inject(CommentViewHolder __);
  void inject(CurrentUser __);
  void inject(Koala __);
  void inject(DiscoveryActivity __);
  void inject(DiscoveryFilterPresenter __);
  void inject(DiscoveryFilterViewHolder __);
  void inject(DiscoveryPresenter __);
  void inject(DiscoveryToolbar __);
  void inject(EmptyActivityFeedViewHolder __);
  void inject(EmptyCommentFeedViewHolder __);
  void inject(FacebookConfirmationPresenter __);
  void inject(ResetPasswordPresenter __);
  void inject(HelpActivity __);
  void inject(IconTextView __);
  void inject(KoalaTrackingClient __);
  void inject(KSWebView __);
  void inject(KSApplication __);
  void inject(LoginPresenter __);
  void inject(LoginToutPresenter __);
  void inject(MessageService __);
  void inject(Money __);
  void inject(ProfileActivity __);
  void inject(ProfilePresenter __);
  void inject(ProjectContextViewHolder __);
  void inject(ProjectActivity __);
  void inject(ProjectPresenter __);
  void inject(ProjectCardViewHolder __);
  void inject(ProjectStateChangedPositiveViewHolder __);
  void inject(ProjectViewHolder __);
  void inject(RegisterService __);
  void inject(RewardViewHolder __);
  void inject(SearchPresenter __);
  void inject(SignupPresenter __);
  void inject(ThanksPresenter __);
  void inject(TwoFactorPresenter __);
  void inject(ViewPledgeActivity __);
  void inject(ViewPledgePresenter __);
}
