# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

$LOAD_PATH << '../lib'
require 'milkrun'

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "416135f4-dacf-4e7b-958c-f49d4e7dcb71"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :update_strings do
  Milkrun::ServerConfigRefresher.new(local: false).refresh
  Milkrun::I18nStringResources.new.create

  current_branch = git_branch

  push_to_git_remote(
    remote: "oss",         # optional, default: "origin"
    local_branch: current_branch,  # optional, aliased by "branch", default: "master"
    force: true,    # optional, default: false
    tags: false     # optional, default: true
  )
end

lane :alpha do
  gradle(task: "assembleInternalPre21Debug")
  slack(
    slack_url: ENV["slack_webhook"],
    message: "Internal debug build successfully delivered!"
    )

  crashlytics(
    api_token: ENV["apiKey"],
    build_secret: ENV["apiSecret"],
    notifications: true
    )
end

lane :external do
  build_android_app(task: "assembleExternalPre21Release")
  slack(
    slack_url: Milkrun::SlackWebhookExtractor.new.webhook,
    message: "External debug build successfully delivered!"
    )

    crashlytics(
      api_token: Milkrun::FabricCredentialsExtractor.new.api_key,
      build_secret: Milkrun::FabricCredentialsExtractor.new.api_secret,
      notifications: true
      )
end

lane :internal do
  build_android_app(task: "assembleInternalPre21Release")

  crashlytics(
    api_token: Milkrun::FabricCredentialsExtractor.new.api_key,
    build_secret: Milkrun::FabricCredentialsExtractor.new.api_secret,
    notifications: true
    )

  slack(
    slack_url: Milkrun::SlackWebhookExtractor.new.webhook,
    message: "Internal release build successfully delivered!"
    )
end
