#!/usr/bin/env sh

ANDROID_STUDIO_PREFERENCES_PATH="${HOME}/Library/Preferences/AndroidStudio"

if [ ! -d $ANDROID_STUDIO_PREFERENCES_PATH ]; then
  echo "Android Studio expected in ${ANDROID_STUDIO_PREFERENCES_PATH}"
  exit 1
fi

# Update Kickstarter style
ANDROID_STYLE_PATH="${ANDROID_STUDIO_PREFERENCES_PATH}/codestyles/Kickstarter.xml"
REPOSITORY_STYLE_PATH="script/style/Kickstarter.xml"

cmp -s "${ANDROID_STYLE_PATH}" "${REPOSITORY_STYLE_PATH}"
if [ $? -ne 0 ]; then
  if [ ! -f $ANDROID_STYLE_PATH ]; then
    echo "Created Android Studio code style, change to the Kickstarter scheme in Preferences > Code Style"
  else
    echo "Updated Kickstarter style, restart Android Studio to apply changes"
  fi
  cp $REPOSITORY_STYLE_PATH $ANDROID_STYLE_PATH
fi

# Remove author from new files
cat /dev/null > "${ANDROID_STUDIO_PREFERENCES_PATH}/fileTemplates/includes/File Header.java"

# Install/update pidcat. Can also install pidcat via brew, but it's way out of date
curl -s "https://raw.githubusercontent.com/JakeWharton/pidcat/660a8197f55cd7bc53f53a2b34014ac6df1c0ceb/pidcat.py" > /tmp/pidcat
chmod +x /tmp/pidcat
cmp -s /tmp/pidcat /usr/local/bin/pidcat
if [ $? -ne 0 ]; then
  echo "Updating pidcat"
  mv /tmp/pidcat /usr/local/bin/pidcat
fi

echo "Bootstrap complete!"
