package com.kickstarter.ui

object IntentKey {
    /*
   * Names require package prefix:
   * http://developer.android.com/reference/android/content/Intent.html#putExtra%28java.lang.String,%20boolean%29
   */
    const val BACKER = "com.kickstarter.kickstarter.intent_backer"
    const val BACKING = "com.kickstarter.kickstarter.intent_backing"
    const val CHECKOUT_DATA = "com.kickstarter.kickstarter.intent_checkout_data"
    const val DISCOVERY_PARAMS = "com.kickstarter.kickstarter.intent_discovery_params"
    const val EDITORIAL = "com.kickstarter.kickstarter.intent_editorial"
    const val EMAIL = "com.kickstarter.kickstarter.intent_email"
    const val EXPAND_PLEDGE_SHEET = "com.kickstarter.kickstarter.intent_expand_pledge_sheet"
    const val FACEBOOK_LOGIN = "com.kickstarter.kickstarter.intent_facebook_login"
    const val FACEBOOK_TOKEN = "com.kickstarter.kickstarter.intent_facebook_token"
    const val FACEBOOK_USER = "com.kickstarter.kickstarter.intent_facebook_user"
    const val INTERNAL_BUILD_ENVELOPE = "com.kickstarter.kickstarter.intent_internal_build_envelope"
    const val IS_FROM_MESSAGES_ACTIVITY = "com.kickstarter.kickstarter.intent_is_from_messages_activity"
    const val MESSAGE_SCREEN_SOURCE_CONTEXT = "com.kickstarter.kickstarter.intent_message_screen_source"
    const val EVENT_DATA = "com.kickstarter.kickstarter.intent_event_data"
    const val EVENT_NAME = "com.kickstarter.kickstarter.intent_event_name"
    const val LOGIN_REASON = "com.kickstarter.kickstarter.intent_login_reason"
    const val MESSAGE_THREAD = "com.kickstarter.kickstarter.intent_message_thread"
    const val PASSWORD = "com.kickstarter.kickstarter.intent_password"
    const val PLEDGE_DATA = "com.kickstarter.kickstarter.intent_pledge_data"
    const val PROJECT = "com.kickstarter.kickstarter.intent_project"
    const val PROJECT_DATA = "com.kickstarter.kickstarter.intent_project_data"
    const val PROJECT_PARAM = "com.kickstarter.kickstarter.intent_project_param"
    const val PUSH_TOKEN = "com.kickstarter.kickstarter.intent_push_token"
    const val REF_TAG = "com.kickstarter.kickstarter.ref_tag"
    const val SURVEY_RESPONSE = "com.kickstarter.kickstarter.survey_response"
    const val NOTIFICATION_SURVEY_RESPONSE = "com.kickstarter.kickstarter.survey_response"
    const val DEEPLINK_SURVEY_RESPONSE = "com.kickstarter.kickstarter.deeplink_survey_response"
    const val NOTIFICATION_PLEDGE_REDEMPTION = "com.kickstarter.kickstarter.notification_pledge_redeption"
    const val TOOLBAR_TITLE = "com.kickstarter.kickstarter.intent_toolbar_title"
    const val TRACKING_CLIENT_TYPE_TAG = "com.kickstarter.kickstarter.intent_tracking_client_tag"
    const val UPDATE = "com.kickstarter.kickstarter.intent_update"
    const val UPDATE_POST_ID = "com.kickstarter.kickstarter.intent_update_post_id"
    const val IS_UPDATE_COMMENT = "com.kickstarter.kickstarter.intent_is_update_comment"
    const val URL = "com.kickstarter.kickstarter.intent_url"
    const val PUSH_NOTIFICATION_ENVELOPE = "com.kickstarter.kickstarter.push_notification_envelope"
    const val COMMENT = "com.kickstarter.kickstarter.intent_comment"
    const val COMMENT_CARD_DATA = "com.kickstarter.kickstarter.intent_comment_card_data"
    const val REPLY_EXPAND = "com.kickstarter.kickstarter.intent_reply_expand"
    const val REPLY_SCROLL_BOTTOM = "com.kickstarter.kickstarter.intent_reply_scroll_bottom"
    const val DEEP_LINK_SCREEN_PROJECT_COMMENT =
        "com.kickstarter.kickstarter.deep_link_screen_project_comment"
    const val DEEP_LINK_SCREEN_PROJECT_SAVE = "com.kickstarter.kickstarter.save"
    const val SAVE_FLAG_VALUE = "com.kickstarter.kickstarter.intent_save_flag_value"
    const val DEEP_LINK_SCREEN_PROJECT_UPDATE =
        "com.kickstarter.kickstarter.deep_link_screen_project_update"
    const val DEEP_LINK_SCREEN_PROJECT_UPDATE_COMMENT =
        "com.kickstarter.kickstarter.deep_link_screen_project_update_comment"
    const val VIDEO_SEEK_POSITION = "com.kickstarter.kickstarter.intent_video_seek_position"
    const val VIDEO_URL_SOURCE = "com.kickstarter.kickstarter.intent_video_SOURCE"
    const val RESET_PASSWORD_FACEBOOK_LOGIN = "com.kickstarter.kickstarter.intent_reset_password_facebook"
    const val FLAGGINGKIND = "com.kickstarter.kickstarter.intent_report_project"
    const val PREVIOUS_SCREEN = "com.kickstarter.kickstarter.previous_screen"
    const val OAUTH_REDIRECT_URL = "com.kickstarter.kickstarter.oauth_redirect_url"
    const val REFRESH_PPO_LIST = "com.kickstarter.kickstarter.refresh_ppo_list"
}
